console.log("Hello World")
console.log("HH    HH             111   111                                             111         dd   !!!")
console.log("HH    HH     eee     111   111     oooo   ww         ww    oooo   rr  rr   111         dd   !!!")
console.log("HHHHHHHH   ee   e    111   111   oo   oo  ww         ww  oo   oo  rrr   r  111     dddddd   !!!")
console.log("HH    HH   eeeee     111   111   oo   oo   ww   ww  ww   oo   oo  rr       111    dd   dd   !!!")
console.log("HH    HH    eeeeeee  111   111    oooo       ww   ww      oooo    rr       111     dddddd   !!! ")
